### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by Leask** [cluries/Tw2other#1]
Class 'Template' not found in /tw2other/modules/init/func.inc.php on line 76

**Comment by cluries** [comment]
额，晚上回去检查下。

**Comment by guiguan** [comment]
我也遇到这个问题：Class 'Template' not found in /tw2other/modules/init/func.inc.php on line 76。貌似Loader的autoload不成功啊。

**Comment by guiguan** [comment]
Hey, here are my patches to fix this problem: http://www.guiguan.net/patches-for-tw2other-1-0-by-cluries-on-github/

**Comment by Leask** [comment]
Make a pull requests.   :)

**Comment by guiguan** [comment]
Okay. Already did :P

**Comment by Leask** [comment]
Cool! thanks @guiguan!

**Comment by Zola** [comment]
same issue :  Fatal error: Class 'Template' not found in /home/zola/zuo.la/tw2other/modules/init/func.inc.php on line 76
