### ISSUE TITLE
赶紧加油啊...

### ISSUE THREAD

**Issue by nonozone** [cluries/Tw2other#2]
等着更新神马的...

**Comment by cluries** [comment]
现在这个架子应该可以用把。。 你不能运行么？

**Comment by nonozone** [comment]
呃，现在用的是老版，饭否一直没法用啊，然后其实不知道为什么163用了一段时间就用不了了，后来不得不用fanfou同步到163，现在饭否也一直用不了，所以一直等新版出来呢。

On Tue, May 15, 2012 at 6:05 PM, cluries <
reply@reply.github.com

> wrote:
> 
> 现在这个架子应该可以用把。。 你不能运行么？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cluries/Tw2other/issues/2#issuecomment-5712458

## 

P Please consider the environment before printing this e-mail
P 纸张，无草木不可得；邮件，非打印犹可读；请关爱环境
