### ISSUE TITLE
install.php 能安装，但是会报错

### ISSUE THREAD

**Issue by rexzhang** [cluries/Tw2other#5]
(mod_fastcgi.c.2701) FastCGI-stderr: PHP Fatal error:  Cannot break/continue 1 level in /home/rex/tw2other/Tw2other/modules/install/authjmpAction.php on line 43

在每认证完一个以后没有跳转，需要重新使用浏览器访问 install.php

**Comment by cluries** [comment]
囧，这里写错了。。。
