### ISSUE TITLE
将0.9x的 tweet.id 和 update.time 复制到 1.0 后 cron.php 无效

### ISSUE THREAD

**Issue by rexzhang** [cluries/Tw2other#6]
查看 浏览器访问 cron.php 的日志是正常的，但是 tweet.id 和 update.time 的内容和日期未改变（有新推、lighttpd有修改这两个文件的权限），同时内容也没有同步到 新浪和腾讯微博

**Comment by cluries** [comment]
1.0中不从这2个文件中读取了，新浪现在是更新不鸟的，腾讯应该可以。

**Comment by rexzhang** [comment]
腾讯微博找到原因了，需要在 cron.php 中调用 run.php 
能否将这些需要人工设置的都整合了？一个 index.php 一个 cron.php 一个可以通过设置禁止的 install.php
